### ISSUE TITLE
新しいバージョンのサポートお願いします。

### ISSUE THREAD

**Issue by nobu02** [progre/ausettings#2]
便利なツールでよく使用させていただいていました。
先日のアップデートで使用できなくなってしまったため対応いただけると幸いです。

**Comment by progre** [comment]
報告ありがとうございます。

amonguscapture のアップデートに連動して使用できるようになりました。
今のバージョンでそのまま利用できるので確認してみてください。

**Comment by nobu02** [comment]
ありがとうございます！部屋設定で変わっているのは確認しました！
